ignore_merge_commits = true
tag_prefix = "v"

pre_bump_hooks = []
post_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []
template = "remote"
remote = "github.com"
repository = "km-crates-publish-test"
owner = "kristof-mattei"

[bump_profiles]
